//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobQuest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public Job()
        {
            this.JobApplications = new HashSet<JobApplication>();
            this.Notifications = new HashSet<Notification>();
        }
    
        public int JobID { get; set; }
        public int RecruiterID { get; set; }
        public string Title { get; set; }
        public string Type { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string Description { get; set; }
        public string Location { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<bool> IsPublished { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Recruiter Recruiter { get; set; }
        public virtual ICollection<JobApplication> JobApplications { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
    }
}
