//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobQuest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobApplication
    {
        public JobApplication()
        {
            this.Documents = new HashSet<Document>();
            this.Notifications = new HashSet<Notification>();
        }
    
        public int JobApplicationID { get; set; }
        public int JobID { get; set; }
        public Nullable<int> JobSeekerID { get; set; }
        public Nullable<System.DateTime> AppliedDate { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<Document> Documents { get; set; }
        public virtual Job Job { get; set; }
        public virtual JobSeeker JobSeeker { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
    }
}
