//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobQuest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int NotificationID { get; set; }
        public int JobID { get; set; }
        public string Status { get; set; }
        public Nullable<int> JobApplicationID { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string NotificationMessage { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual JobApplication JobApplication { get; set; }
    }
}
